- spec/NetexplorerProxy+config.json
- spec/NetexplorerProxy+forwardings.yaml
- spec/NetexplorerProxy+profileInstances.yaml
- spec/NetexplorerProxy+services.yaml
- spec/NetexplorerProxy.yaml
> Kmohr-soprasteria/issue3

- spec/NetexplorerProxy+forwardings.yaml
- spec/NetexplorerProxy+profileInstances.yaml
- spec/NetexplorerProxy+profiles.yaml
> Create profileList, profileInstancesList and forwardingList

- spec/NetexplorerProxy.yaml
> Error in /v1/receive-current-mac-table-of-device requestBody

- spec/NetexplorerProxy+config.json
- spec/NetexplorerProxy+services.yaml
- spec/NetexplorerProxy.yaml
> Simplify read-current-mac-table service requestBody

- spec/NetexplorerProxy+config.json
> Operation-client definition missing for nep-1-0-0-op-c-is-matr-1-0-3-002

- spec/NetexplorerProxy+config.json
- spec/NetexplorerProxy+forwardings.yaml
- spec/NetexplorerProxy+profileInstances.yaml
- spec/NetexplorerProxy+services.yaml
- spec/NetexplorerProxy.yaml
- spec/diagrams/002_ReadCurrentMacTableFromDevice.plantuml
> Update release info in spec to 1.0.1

- spec/NetexplorerProxy.yaml
> Add >required< statements to requestBodies/responseBodies where missing

- spec/NetexplorerProxy.yaml
> Update components/responseCodes with predefined responseCodes from appPattern documentation

- README.md
> Update readme with description for new MWDI data

- spec/NetexplorerProxy+config.json
- spec/NetexplorerProxy+forwardings.yaml
- spec/NetexplorerProxy+profileInstances.yaml
- spec/NetexplorerProxy+services.yaml
- spec/NetexplorerProxy.yaml
- spec/diagrams/012_ReadCurrentMacTableFromDevice.plantuml
> Update to nep-1-1-0

- spec/NetexplorerProxy.yaml
> Change optional filter for new services data-age from days to hours

- spec/additionalDescription/_AirInterfaceMappings.md
> Fix additional description data example

- spec/additionalDescription/CyclicDataRetrievalProcess.md
> Add filter description for (airIf) transmissionModeLists

- spec/NetexplorerProxy.yaml
> Add improved descriptions for the new services that return csv data

- spec/NetexplorerProxy.yaml
> Change MAC services to cope with missing attribute values in returned MATR data in 1.1.0_spec

- spec/NetexplorerProxy+config.json
- spec/NetexplorerProxy+forwardings.yaml
- spec/NetexplorerProxy+services.yaml
- spec/NetexplorerProxy.yaml
> Correct oldRelease info from 1.0.1 to 1.0.2

- server/service/IndividualServicesService.js
use operation ley for /v1/receive-current-mac-table-of-device
> NEP issue #110 part 1

- server/service/individualServices/RequestHandler.js
use operation ley for /v1/receive-current-mac-table-of-device
> NEP issue #110 part 2

- server/controllers/IndividualServices.js
- server/service/IndividualServicesService.js
- server/service/db/airIfClass.js
- server/service/db/airTransModeClass.js
- server/service/db/dbHandler.js
- server/service/db/devicesGeneralInfoClass.js
- server/service/db/equipmentClass.js
- server/service/db/ethContClass.js
- server/service/db/wireIfClass.js
Implementing issue #193 - To implement service: /v1/provide-general-information-of-devices
> Latta siae/issue193

- spec/NetexplorerProxy.yaml
> Add meta info in oas (fixes #201)

- README.md
- spec/NetexplorerProxy+config.json
- spec/NetexplorerProxy+profileInstances.yaml
> Add a new genericResponseProfile instance

- server/controllers/IndividualServices.js
Fix controller file to manage better exception
> Fix error handler

- server/index.js
- server/package-lock.json
- server/package.json
- server/service/IndividualServicesService.js
- server/service/ProcessMountNames.js
- server/service/db/dbHandler.js
- testing/README.md
Fixing code to make it working properly
- dynamic connection sqlite/mariaDB based on ENV variable
- Fix timestamp format
- Fix JSON format that isn't complaint with openapi validation (provideListOfDevicesInNep)
- Remove unused JS library (postgresql, mysql)
- Fix timestamp where condition
- Adding routine that create DB if doesn't exists
> Latta siae/bf maria db connection

- .vscode/launch.json
- server/index.js
- server/service/db/dbHandler.js
Adding external DB connection (MariaDB)
> Latta siae/bf init db

- spec/additionalDescription/_AirInterfaceMappings.md
- spec/additionalDescription/_EthernetContainerMappings.md
- spec/additionalDescription/_WireInterfaceMappings.md
> Fix wrong descriptions for how to trim state information.

- server/index.js
- server/service/BasicServicesService.js
- server/service/ProcessMountNames.js
- server/service/db/dbHandler.js
Fixing parameters from environment
Trim response data
Drop data with coderate = -1
Fixing timestamp filter
> Latta siae/bf cyclic improvement
